language: node_js
node_js:
  - "4"
  - "5"
  - "6"
script:
  - npm run test
  - npm run build
  - npm run check:examples
branches:
  only:
    - master
    - /^greenkeeper-.*$/
    - /^greenkeeper/.*$/
cache:
  directories:
  - $HOME/.npm
  - examples/header-footer/node_modules
